### ISSUE TITLE
Escape special chars

### ISSUE THREAD

**Issue by lex111** [DanielRuf/html-minifier-terser#28]
Hi @DanielRuf 

Try it out https://danielruf.github.io/html-minifier-terser/

```
<h2><a aria-hidden="true" tabindex="-1" class="anchor" id="initial-setup--8"></a><a aria-hidden="true" tabindex="-1" class="hash-link" href="#initial-setup--8" title="Direct link to heading">#</a><div>Initial setup < 8</div></h2>
```

Output:

> Error: Parse Error: < 8</div></h2>

How to avoid this? Is it possible to escape special characters?

**Comment by DanielRuf** [comment]
> Initial setup < 8

This is not valid HTML, you have to use `&lt;`.

**Comment by DanielRuf** [comment]
![Screenshot_20200121-200422](https://user-images.githubusercontent.com/827205/72834473-38d6aa80-3c89-11ea-9a54-5492b5bdadd3.jpg)

html-minifier-terser does not do any encoding and can not do. Because how should it know which characters should be encoded.

This is out of the scope of this library, you have to do it yourself and ensure that the markup is valid.

**Comment by lex111** [comment]
OK, thank you for your work!
