### ISSUE TITLE
no CHANGELOG and release notes

### ISSUE THREAD

**Issue by evilebottnawi** [DanielRuf/html-minifier-terser#43]
It's pretty hard to understand what has changed and fixed, will be great to have CHANGELOG or release notes on each version in future

**Comment by DanielRuf** [comment]
Hi @evilebottnawi,

thanks for the proposal. What solutions do you recommend to automate / ease the process of creating these?

Manually maintaining them is often a big time factor and combined with much (manual) work and as there is no commit message convention used so far it might not be possible to generate these (so manual work is still needed).

**Comment by evilebottnawi** [comment]
Maybe use `commit message convention` and generate it from commit messages, this is the easiest way

**Comment by DanielRuf** [comment]
Do you mean https://www.conventionalcommits.org for future commits and releases with the rules from Angular and others? We would have to enforce them then.

I guess you do not need it for previous releases. Because creating a changelog for them will be very time consuming and no one pays my time for this.

**Comment by DanielRuf** [comment]
Do you mean https://www.conventionalcommits.org for future commits and releases with the rules from Angular and others? This is what I had in my mind. We would have to enforce them then.

I guess you do not need it for previous releases. Because creating a changelog for them will be very time consuming and no one pays my time for this.

**Comment by natterstefan** [comment]
> I guess you do not need it for previous releases. Because creating a changelog for them will be very time consuming and no one pays my time for this.

I agree with you @DanielRuf, but can you come up with an ETA for a Changelog? Whilst updating some dependencies in our app, a new version of your package was highlighted. We wonder what's new and saw this PR.

A Changelog would be very helpful and I'm happy to help integrating e.g. [commitizen](https://github.com/commitizen/cz-cli) and [standard-version](https://github.com/conventional-changelog/standard-version) (see [my example repo](https://github.com/natterstefan/example-commitizen-standard-version)).

Thanks for your time. Take care.

**Comment by DanielRuf** [comment]
No ETA from my side so far. PRs are very welcome. Currently paid work is more important. When I find some time I can maybe work on that.

> We wonder what's new and saw this issue.

You should be able to see the commits since each release.

**Comment by DanielRuf** [comment]
I have added a few descriptions to the releases which link the relevant commits, the dependency updates are not relevant imo.

https://github.com/danielruf/html-minifier-terser/releases

I think this should be sufficient for now.
If not feel free to provide PRs or mention commits that you miss in the release descriptions.
